<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: contact.proto

namespace Wechaty\Puppet;

use UnexpectedValueException;

/**
 * Protobuf type <code>wechaty.puppet.ContactType</code>
 */
class ContactType
{
    /**
     * Generated from protobuf enum <code>CONTACT_TYPE_UNSPECIFIED = 0;</code>
     */
    const CONTACT_TYPE_UNSPECIFIED = 0;
    /**
     * Generated from protobuf enum <code>CONTACT_TYPE_PERSONAL = 1;</code>
     */
    const CONTACT_TYPE_PERSONAL = 1;
    /**
     * Generated from protobuf enum <code>CONTACT_TYPE_OFFICIAL = 2;</code>
     */
    const CONTACT_TYPE_OFFICIAL = 2;

    private static $valueToName = [
        self::CONTACT_TYPE_UNSPECIFIED => 'CONTACT_TYPE_UNSPECIFIED',
        self::CONTACT_TYPE_PERSONAL => 'CONTACT_TYPE_PERSONAL',
        self::CONTACT_TYPE_OFFICIAL => 'CONTACT_TYPE_OFFICIAL',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

