<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: event.proto

namespace Wechaty\Puppet;

use UnexpectedValueException;

/**
 * Protobuf type <code>wechaty.puppet.EventType</code>
 */
class EventType
{
    /**
     * Generated from protobuf enum <code>EVENT_TYPE_UNSPECIFIED = 0;</code>
     */
    const EVENT_TYPE_UNSPECIFIED = 0;
    /**
     * Generated from protobuf enum <code>EVENT_TYPE_HEARTBEAT = 1;</code>
     */
    const EVENT_TYPE_HEARTBEAT = 1;
    /**
     * Generated from protobuf enum <code>EVENT_TYPE_MESSAGE = 2;</code>
     */
    const EVENT_TYPE_MESSAGE = 2;
    /**
     * Generated from protobuf enum <code>EVENT_TYPE_DONG = 3;</code>
     */
    const EVENT_TYPE_DONG = 3;
    /**
     * Generated from protobuf enum <code>EVENT_TYPE_ERROR = 16;</code>
     */
    const EVENT_TYPE_ERROR = 16;
    /**
     * Generated from protobuf enum <code>EVENT_TYPE_FRIENDSHIP = 17;</code>
     */
    const EVENT_TYPE_FRIENDSHIP = 17;
    /**
     * Generated from protobuf enum <code>EVENT_TYPE_ROOM_INVITE = 18;</code>
     */
    const EVENT_TYPE_ROOM_INVITE = 18;
    /**
     * Generated from protobuf enum <code>EVENT_TYPE_ROOM_JOIN = 19;</code>
     */
    const EVENT_TYPE_ROOM_JOIN = 19;
    /**
     * Generated from protobuf enum <code>EVENT_TYPE_ROOM_LEAVE = 20;</code>
     */
    const EVENT_TYPE_ROOM_LEAVE = 20;
    /**
     * Generated from protobuf enum <code>EVENT_TYPE_ROOM_TOPIC = 21;</code>
     */
    const EVENT_TYPE_ROOM_TOPIC = 21;
    /**
     * Generated from protobuf enum <code>EVENT_TYPE_SCAN = 22;</code>
     */
    const EVENT_TYPE_SCAN = 22;
    /**
     * Generated from protobuf enum <code>EVENT_TYPE_READY = 23;</code>
     */
    const EVENT_TYPE_READY = 23;
    /**
     * Generated from protobuf enum <code>EVENT_TYPE_RESET = 24;</code>
     */
    const EVENT_TYPE_RESET = 24;
    /**
     * Generated from protobuf enum <code>EVENT_TYPE_LOGIN = 25;</code>
     */
    const EVENT_TYPE_LOGIN = 25;
    /**
     * Generated from protobuf enum <code>EVENT_TYPE_LOGOUT = 26;</code>
     */
    const EVENT_TYPE_LOGOUT = 26;

    private static $valueToName = [
        self::EVENT_TYPE_UNSPECIFIED => 'EVENT_TYPE_UNSPECIFIED',
        self::EVENT_TYPE_HEARTBEAT => 'EVENT_TYPE_HEARTBEAT',
        self::EVENT_TYPE_MESSAGE => 'EVENT_TYPE_MESSAGE',
        self::EVENT_TYPE_DONG => 'EVENT_TYPE_DONG',
        self::EVENT_TYPE_ERROR => 'EVENT_TYPE_ERROR',
        self::EVENT_TYPE_FRIENDSHIP => 'EVENT_TYPE_FRIENDSHIP',
        self::EVENT_TYPE_ROOM_INVITE => 'EVENT_TYPE_ROOM_INVITE',
        self::EVENT_TYPE_ROOM_JOIN => 'EVENT_TYPE_ROOM_JOIN',
        self::EVENT_TYPE_ROOM_LEAVE => 'EVENT_TYPE_ROOM_LEAVE',
        self::EVENT_TYPE_ROOM_TOPIC => 'EVENT_TYPE_ROOM_TOPIC',
        self::EVENT_TYPE_SCAN => 'EVENT_TYPE_SCAN',
        self::EVENT_TYPE_READY => 'EVENT_TYPE_READY',
        self::EVENT_TYPE_RESET => 'EVENT_TYPE_RESET',
        self::EVENT_TYPE_LOGIN => 'EVENT_TYPE_LOGIN',
        self::EVENT_TYPE_LOGOUT => 'EVENT_TYPE_LOGOUT',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

