<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: friendship.proto

namespace Wechaty\Puppet;

use UnexpectedValueException;

/**
 * Protobuf type <code>wechaty.puppet.FriendshipSceneType</code>
 */
class FriendshipSceneType
{
    /**
     * Generated from protobuf enum <code>FRIENDSHIP_SCENE_TYPE_UNSPECIFIED = 0;</code>
     */
    const FRIENDSHIP_SCENE_TYPE_UNSPECIFIED = 0;
    /**
     * Generated from protobuf enum <code>FRIENDSHIP_SCENE_TYPE_QQ = 1;</code>
     */
    const FRIENDSHIP_SCENE_TYPE_QQ = 1;
    /**
     * Generated from protobuf enum <code>FRIENDSHIP_SCENE_TYPE_EMAIL = 2;</code>
     */
    const FRIENDSHIP_SCENE_TYPE_EMAIL = 2;
    /**
     * Generated from protobuf enum <code>FRIENDSHIP_SCENE_TYPE_WEIXIN = 3;</code>
     */
    const FRIENDSHIP_SCENE_TYPE_WEIXIN = 3;
    /**
     * Generated from protobuf enum <code>FRIENDSHIP_SCENE_TYPE_QQTBD = 12;</code>
     */
    const FRIENDSHIP_SCENE_TYPE_QQTBD = 12;
    /**
     * Generated from protobuf enum <code>FRIENDSHIP_SCENE_TYPE_ROOM = 14;</code>
     */
    const FRIENDSHIP_SCENE_TYPE_ROOM = 14;
    /**
     * Generated from protobuf enum <code>FRIENDSHIP_SCENE_TYPE_PHONE = 15;</code>
     */
    const FRIENDSHIP_SCENE_TYPE_PHONE = 15;
    /**
     * Generated from protobuf enum <code>FRIENDSHIP_SCENE_TYPE_CARD = 17;</code>
     */
    const FRIENDSHIP_SCENE_TYPE_CARD = 17;
    /**
     * Generated from protobuf enum <code>FRIENDSHIP_SCENE_TYPE_LOCATION = 18;</code>
     */
    const FRIENDSHIP_SCENE_TYPE_LOCATION = 18;
    /**
     * Generated from protobuf enum <code>FRIENDSHIP_SCENE_TYPE_BOTTLE = 25;</code>
     */
    const FRIENDSHIP_SCENE_TYPE_BOTTLE = 25;
    /**
     * Generated from protobuf enum <code>FRIENDSHIP_SCENE_TYPE_SHAKING = 29;</code>
     */
    const FRIENDSHIP_SCENE_TYPE_SHAKING = 29;
    /**
     * Generated from protobuf enum <code>FRIENDSHIP_SCENE_TYPE_QRCODE = 30;</code>
     */
    const FRIENDSHIP_SCENE_TYPE_QRCODE = 30;

    private static $valueToName = [
        self::FRIENDSHIP_SCENE_TYPE_UNSPECIFIED => 'FRIENDSHIP_SCENE_TYPE_UNSPECIFIED',
        self::FRIENDSHIP_SCENE_TYPE_QQ => 'FRIENDSHIP_SCENE_TYPE_QQ',
        self::FRIENDSHIP_SCENE_TYPE_EMAIL => 'FRIENDSHIP_SCENE_TYPE_EMAIL',
        self::FRIENDSHIP_SCENE_TYPE_WEIXIN => 'FRIENDSHIP_SCENE_TYPE_WEIXIN',
        self::FRIENDSHIP_SCENE_TYPE_QQTBD => 'FRIENDSHIP_SCENE_TYPE_QQTBD',
        self::FRIENDSHIP_SCENE_TYPE_ROOM => 'FRIENDSHIP_SCENE_TYPE_ROOM',
        self::FRIENDSHIP_SCENE_TYPE_PHONE => 'FRIENDSHIP_SCENE_TYPE_PHONE',
        self::FRIENDSHIP_SCENE_TYPE_CARD => 'FRIENDSHIP_SCENE_TYPE_CARD',
        self::FRIENDSHIP_SCENE_TYPE_LOCATION => 'FRIENDSHIP_SCENE_TYPE_LOCATION',
        self::FRIENDSHIP_SCENE_TYPE_BOTTLE => 'FRIENDSHIP_SCENE_TYPE_BOTTLE',
        self::FRIENDSHIP_SCENE_TYPE_SHAKING => 'FRIENDSHIP_SCENE_TYPE_SHAKING',
        self::FRIENDSHIP_SCENE_TYPE_QRCODE => 'FRIENDSHIP_SCENE_TYPE_QRCODE',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

