<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: friendship.proto

namespace Wechaty\Puppet;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>wechaty.puppet.FriendshipAddRequest</code>
 */
class FriendshipAddRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string contact_id = 1;</code>
     */
    protected $contact_id = '';
    /**
     * Generated from protobuf field <code>string hello = 2;</code>
     */
    protected $hello = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $contact_id
     *     @type string $hello
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Friendship::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string contact_id = 1;</code>
     * @return string
     */
    public function getContactId()
    {
        return $this->contact_id;
    }

    /**
     * Generated from protobuf field <code>string contact_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setContactId($var)
    {
        GPBUtil::checkString($var, True);
        $this->contact_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string hello = 2;</code>
     * @return string
     */
    public function getHello()
    {
        return $this->hello;
    }

    /**
     * Generated from protobuf field <code>string hello = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setHello($var)
    {
        GPBUtil::checkString($var, True);
        $this->hello = $var;

        return $this;
    }

}

