<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: friendship.proto

namespace Wechaty\Puppet;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>wechaty.puppet.FriendshipPayloadResponse</code>
 */
class FriendshipPayloadResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string id = 1;</code>
     */
    protected $id = '';
    /**
     * Generated from protobuf field <code>string contact_id = 2;</code>
     */
    protected $contact_id = '';
    /**
     * Generated from protobuf field <code>string hello = 3;</code>
     */
    protected $hello = '';
    /**
     * Generated from protobuf field <code>.wechaty.puppet.FriendshipType type = 4;</code>
     */
    protected $type = 0;
    /**
     * Generated from protobuf field <code>string stranger = 5;</code>
     */
    protected $stranger = '';
    /**
     * Generated from protobuf field <code>string ticket = 6;</code>
     */
    protected $ticket = '';
    /**
     * Generated from protobuf field <code>.wechaty.puppet.FriendshipSceneType scene = 7;</code>
     */
    protected $scene = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $id
     *     @type string $contact_id
     *     @type string $hello
     *     @type int $type
     *     @type string $stranger
     *     @type string $ticket
     *     @type int $scene
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Friendship::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, True);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string contact_id = 2;</code>
     * @return string
     */
    public function getContactId()
    {
        return $this->contact_id;
    }

    /**
     * Generated from protobuf field <code>string contact_id = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setContactId($var)
    {
        GPBUtil::checkString($var, True);
        $this->contact_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string hello = 3;</code>
     * @return string
     */
    public function getHello()
    {
        return $this->hello;
    }

    /**
     * Generated from protobuf field <code>string hello = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setHello($var)
    {
        GPBUtil::checkString($var, True);
        $this->hello = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.wechaty.puppet.FriendshipType type = 4;</code>
     * @return int
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Generated from protobuf field <code>.wechaty.puppet.FriendshipType type = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkEnum($var, \Wechaty\Puppet\FriendshipType::class);
        $this->type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string stranger = 5;</code>
     * @return string
     */
    public function getStranger()
    {
        return $this->stranger;
    }

    /**
     * Generated from protobuf field <code>string stranger = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setStranger($var)
    {
        GPBUtil::checkString($var, True);
        $this->stranger = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string ticket = 6;</code>
     * @return string
     */
    public function getTicket()
    {
        return $this->ticket;
    }

    /**
     * Generated from protobuf field <code>string ticket = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setTicket($var)
    {
        GPBUtil::checkString($var, True);
        $this->ticket = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.wechaty.puppet.FriendshipSceneType scene = 7;</code>
     * @return int
     */
    public function getScene()
    {
        return $this->scene;
    }

    /**
     * Generated from protobuf field <code>.wechaty.puppet.FriendshipSceneType scene = 7;</code>
     * @param int $var
     * @return $this
     */
    public function setScene($var)
    {
        GPBUtil::checkEnum($var, \Wechaty\Puppet\FriendshipSceneType::class);
        $this->scene = $var;

        return $this;
    }

}

