<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: friendship.proto

namespace Wechaty\Puppet;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>wechaty.puppet.FriendshipSearchWeixinRequest</code>
 */
class FriendshipSearchWeixinRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string weixin = 1;</code>
     */
    protected $weixin = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $weixin
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Friendship::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string weixin = 1;</code>
     * @return string
     */
    public function getWeixin()
    {
        return $this->weixin;
    }

    /**
     * Generated from protobuf field <code>string weixin = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setWeixin($var)
    {
        GPBUtil::checkString($var, True);
        $this->weixin = $var;

        return $this;
    }

}

