<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message.proto

namespace Wechaty\Puppet;

use UnexpectedValueException;

/**
 * Protobuf type <code>wechaty.puppet.ImageType</code>
 */
class ImageType
{
    /**
     * Generated from protobuf enum <code>IMAGE_TYPE_UNSPECIFIED = 0;</code>
     */
    const IMAGE_TYPE_UNSPECIFIED = 0;
    /**
     * Generated from protobuf enum <code>IMAGE_TYPE_THUMBNAIL = 1;</code>
     */
    const IMAGE_TYPE_THUMBNAIL = 1;
    /**
     * Generated from protobuf enum <code>IMAGE_TYPE_HD = 2;</code>
     */
    const IMAGE_TYPE_HD = 2;
    /**
     * Generated from protobuf enum <code>IMAGE_TYPE_ARTWORK = 3;</code>
     */
    const IMAGE_TYPE_ARTWORK = 3;

    private static $valueToName = [
        self::IMAGE_TYPE_UNSPECIFIED => 'IMAGE_TYPE_UNSPECIFIED',
        self::IMAGE_TYPE_THUMBNAIL => 'IMAGE_TYPE_THUMBNAIL',
        self::IMAGE_TYPE_HD => 'IMAGE_TYPE_HD',
        self::IMAGE_TYPE_ARTWORK => 'IMAGE_TYPE_ARTWORK',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

