<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message.proto

namespace Wechaty\Puppet;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>wechaty.puppet.MessagePayloadResponse</code>
 */
class MessagePayloadResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string id = 1;</code>
     */
    protected $id = '';
    /**
     * Generated from protobuf field <code>string filename = 2;</code>
     */
    protected $filename = '';
    /**
     * Generated from protobuf field <code>string text = 3;</code>
     */
    protected $text = '';
    /**
     * Generated from protobuf field <code>uint64 timestamp = 4;</code>
     */
    protected $timestamp = 0;
    /**
     * Generated from protobuf field <code>.wechaty.puppet.MessageType type = 5;</code>
     */
    protected $type = 0;
    /**
     * Generated from protobuf field <code>string from_id = 6;</code>
     */
    protected $from_id = '';
    /**
     * Generated from protobuf field <code>string room_id = 7;</code>
     */
    protected $room_id = '';
    /**
     * Generated from protobuf field <code>string to_id = 8;</code>
     */
    protected $to_id = '';
    /**
     * Generated from protobuf field <code>repeated string mention_ids = 9;</code>
     */
    private $mention_ids;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $id
     *     @type string $filename
     *     @type string $text
     *     @type int|string $timestamp
     *     @type int $type
     *     @type string $from_id
     *     @type string $room_id
     *     @type string $to_id
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $mention_ids
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Message::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, True);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string filename = 2;</code>
     * @return string
     */
    public function getFilename()
    {
        return $this->filename;
    }

    /**
     * Generated from protobuf field <code>string filename = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setFilename($var)
    {
        GPBUtil::checkString($var, True);
        $this->filename = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string text = 3;</code>
     * @return string
     */
    public function getText()
    {
        return $this->text;
    }

    /**
     * Generated from protobuf field <code>string text = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setText($var)
    {
        GPBUtil::checkString($var, True);
        $this->text = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 timestamp = 4;</code>
     * @return int|string
     */
    public function getTimestamp()
    {
        return $this->timestamp;
    }

    /**
     * Generated from protobuf field <code>uint64 timestamp = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTimestamp($var)
    {
        GPBUtil::checkUint64($var);
        $this->timestamp = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.wechaty.puppet.MessageType type = 5;</code>
     * @return int
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Generated from protobuf field <code>.wechaty.puppet.MessageType type = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkEnum($var, \Wechaty\Puppet\MessageType::class);
        $this->type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string from_id = 6;</code>
     * @return string
     */
    public function getFromId()
    {
        return $this->from_id;
    }

    /**
     * Generated from protobuf field <code>string from_id = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setFromId($var)
    {
        GPBUtil::checkString($var, True);
        $this->from_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string room_id = 7;</code>
     * @return string
     */
    public function getRoomId()
    {
        return $this->room_id;
    }

    /**
     * Generated from protobuf field <code>string room_id = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setRoomId($var)
    {
        GPBUtil::checkString($var, True);
        $this->room_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string to_id = 8;</code>
     * @return string
     */
    public function getToId()
    {
        return $this->to_id;
    }

    /**
     * Generated from protobuf field <code>string to_id = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setToId($var)
    {
        GPBUtil::checkString($var, True);
        $this->to_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string mention_ids = 9;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getMentionIds()
    {
        return $this->mention_ids;
    }

    /**
     * Generated from protobuf field <code>repeated string mention_ids = 9;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setMentionIds($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->mention_ids = $arr;

        return $this;
    }

}

