<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message.proto

namespace Wechaty\Puppet;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>wechaty.puppet.MessageSendTextRequest</code>
 */
class MessageSendTextRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string conversation_id = 1;</code>
     */
    protected $conversation_id = '';
    /**
     * Generated from protobuf field <code>string text = 2;</code>
     */
    protected $text = '';
    /**
     * Generated from protobuf field <code>repeated string mentonal_ids = 3;</code>
     */
    private $mentonal_ids;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $conversation_id
     *     @type string $text
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $mentonal_ids
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Message::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string conversation_id = 1;</code>
     * @return string
     */
    public function getConversationId()
    {
        return $this->conversation_id;
    }

    /**
     * Generated from protobuf field <code>string conversation_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setConversationId($var)
    {
        GPBUtil::checkString($var, True);
        $this->conversation_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string text = 2;</code>
     * @return string
     */
    public function getText()
    {
        return $this->text;
    }

    /**
     * Generated from protobuf field <code>string text = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setText($var)
    {
        GPBUtil::checkString($var, True);
        $this->text = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string mentonal_ids = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getMentonalIds()
    {
        return $this->mentonal_ids;
    }

    /**
     * Generated from protobuf field <code>repeated string mentonal_ids = 3;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setMentonalIds($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->mentonal_ids = $arr;

        return $this;
    }

}

