<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message.proto

namespace Wechaty\Puppet;

use UnexpectedValueException;

/**
 * Protobuf type <code>wechaty.puppet.MessageType</code>
 */
class MessageType
{
    /**
     * Generated from protobuf enum <code>MESSAGE_TYPE_UNSPECIFIED = 0;</code>
     */
    const MESSAGE_TYPE_UNSPECIFIED = 0;
    /**
     * Generated from protobuf enum <code>MESSAGE_TYPE_ATTACHMENT = 1;</code>
     */
    const MESSAGE_TYPE_ATTACHMENT = 1;
    /**
     * Generated from protobuf enum <code>MESSAGE_TYPE_AUDIO = 2;</code>
     */
    const MESSAGE_TYPE_AUDIO = 2;
    /**
     * Generated from protobuf enum <code>MESSAGE_TYPE_CONTACT = 3;</code>
     */
    const MESSAGE_TYPE_CONTACT = 3;
    /**
     * Generated from protobuf enum <code>MESSAGE_TYPE_EMOTICON = 4;</code>
     */
    const MESSAGE_TYPE_EMOTICON = 4;
    /**
     * Generated from protobuf enum <code>MESSAGE_TYPE_IMAGE = 5;</code>
     */
    const MESSAGE_TYPE_IMAGE = 5;
    /**
     * Generated from protobuf enum <code>MESSAGE_TYPE_TEXT = 6;</code>
     */
    const MESSAGE_TYPE_TEXT = 6;
    /**
     * Generated from protobuf enum <code>MESSAGE_TYPE_VIDEO = 7;</code>
     */
    const MESSAGE_TYPE_VIDEO = 7;
    /**
     * Generated from protobuf enum <code>MESSAGE_TYPE_CHAT_HISTORY = 8;</code>
     */
    const MESSAGE_TYPE_CHAT_HISTORY = 8;
    /**
     * Generated from protobuf enum <code>MESSAGE_TYPE_LOCATION = 9;</code>
     */
    const MESSAGE_TYPE_LOCATION = 9;
    /**
     * Generated from protobuf enum <code>MESSAGE_TYPE_MINI_PROGRAM = 10;</code>
     */
    const MESSAGE_TYPE_MINI_PROGRAM = 10;
    /**
     * Generated from protobuf enum <code>MESSAGE_TYPE_TRANSFER = 11;</code>
     */
    const MESSAGE_TYPE_TRANSFER = 11;
    /**
     * Generated from protobuf enum <code>MESSAGE_TYPE_RED_ENVELOPE = 12;</code>
     */
    const MESSAGE_TYPE_RED_ENVELOPE = 12;
    /**
     * Generated from protobuf enum <code>MESSAGE_TYPE_RECALLED = 13;</code>
     */
    const MESSAGE_TYPE_RECALLED = 13;
    /**
     * Generated from protobuf enum <code>MESSAGE_TYPE_URL = 14;</code>
     */
    const MESSAGE_TYPE_URL = 14;

    private static $valueToName = [
        self::MESSAGE_TYPE_UNSPECIFIED => 'MESSAGE_TYPE_UNSPECIFIED',
        self::MESSAGE_TYPE_ATTACHMENT => 'MESSAGE_TYPE_ATTACHMENT',
        self::MESSAGE_TYPE_AUDIO => 'MESSAGE_TYPE_AUDIO',
        self::MESSAGE_TYPE_CONTACT => 'MESSAGE_TYPE_CONTACT',
        self::MESSAGE_TYPE_EMOTICON => 'MESSAGE_TYPE_EMOTICON',
        self::MESSAGE_TYPE_IMAGE => 'MESSAGE_TYPE_IMAGE',
        self::MESSAGE_TYPE_TEXT => 'MESSAGE_TYPE_TEXT',
        self::MESSAGE_TYPE_VIDEO => 'MESSAGE_TYPE_VIDEO',
        self::MESSAGE_TYPE_CHAT_HISTORY => 'MESSAGE_TYPE_CHAT_HISTORY',
        self::MESSAGE_TYPE_LOCATION => 'MESSAGE_TYPE_LOCATION',
        self::MESSAGE_TYPE_MINI_PROGRAM => 'MESSAGE_TYPE_MINI_PROGRAM',
        self::MESSAGE_TYPE_TRANSFER => 'MESSAGE_TYPE_TRANSFER',
        self::MESSAGE_TYPE_RED_ENVELOPE => 'MESSAGE_TYPE_RED_ENVELOPE',
        self::MESSAGE_TYPE_RECALLED => 'MESSAGE_TYPE_RECALLED',
        self::MESSAGE_TYPE_URL => 'MESSAGE_TYPE_URL',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

