<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: room.proto

namespace Wechaty\Puppet;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>wechaty.puppet.RoomTopicResponse</code>
 */
class RoomTopicResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.google.protobuf.StringValue topic = 1;</code>
     */
    protected $topic = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Google\Protobuf\StringValue $topic
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Room::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.StringValue topic = 1;</code>
     * @return \Google\Protobuf\StringValue
     */
    public function getTopic()
    {
        return $this->topic;
    }

    /**
     * Returns the unboxed value from <code>getTopic()</code>

     * Generated from protobuf field <code>.google.protobuf.StringValue topic = 1;</code>
     * @return string|null
     */
    public function getTopicUnwrapped()
    {
        return $this->readWrapperValue("topic");
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.StringValue topic = 1;</code>
     * @param \Google\Protobuf\StringValue $var
     * @return $this
     */
    public function setTopic($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\StringValue::class);
        $this->topic = $var;

        return $this;
    }

    /**
     * Sets the field by wrapping a primitive type in a Google\Protobuf\StringValue object.

     * Generated from protobuf field <code>.google.protobuf.StringValue topic = 1;</code>
     * @param string|null $var
     * @return $this
     */
    public function setTopicUnwrapped($var)
    {
        $this->writeWrapperValue("topic", $var);
        return $this;}

}

