<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: room.proto

namespace Wechaty\Puppet;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>wechaty.puppet.RoomPayloadResponse</code>
 */
class RoomPayloadResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string id = 1;</code>
     */
    protected $id = '';
    /**
     * Generated from protobuf field <code>string topic = 2;</code>
     */
    protected $topic = '';
    /**
     * Generated from protobuf field <code>string avatar = 3;</code>
     */
    protected $avatar = '';
    /**
     * Generated from protobuf field <code>string owner_id = 4;</code>
     */
    protected $owner_id = '';
    /**
     * Generated from protobuf field <code>repeated string admin_ids = 5;</code>
     */
    private $admin_ids;
    /**
     * Generated from protobuf field <code>repeated string member_ids = 6;</code>
     */
    private $member_ids;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $id
     *     @type string $topic
     *     @type string $avatar
     *     @type string $owner_id
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $admin_ids
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $member_ids
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Room::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, True);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string topic = 2;</code>
     * @return string
     */
    public function getTopic()
    {
        return $this->topic;
    }

    /**
     * Generated from protobuf field <code>string topic = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setTopic($var)
    {
        GPBUtil::checkString($var, True);
        $this->topic = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string avatar = 3;</code>
     * @return string
     */
    public function getAvatar()
    {
        return $this->avatar;
    }

    /**
     * Generated from protobuf field <code>string avatar = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setAvatar($var)
    {
        GPBUtil::checkString($var, True);
        $this->avatar = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string owner_id = 4;</code>
     * @return string
     */
    public function getOwnerId()
    {
        return $this->owner_id;
    }

    /**
     * Generated from protobuf field <code>string owner_id = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setOwnerId($var)
    {
        GPBUtil::checkString($var, True);
        $this->owner_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string admin_ids = 5;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getAdminIds()
    {
        return $this->admin_ids;
    }

    /**
     * Generated from protobuf field <code>repeated string admin_ids = 5;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setAdminIds($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->admin_ids = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string member_ids = 6;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getMemberIds()
    {
        return $this->member_ids;
    }

    /**
     * Generated from protobuf field <code>repeated string member_ids = 6;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setMemberIds($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->member_ids = $arr;

        return $this;
    }

}

