<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: room_member.proto

namespace Wechaty\Puppet;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>wechaty.puppet.RoomMemberListResponse</code>
 */
class RoomMemberListResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated string member_ids = 1;</code>
     */
    private $member_ids;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $member_ids
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\RoomMember::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated string member_ids = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getMemberIds()
    {
        return $this->member_ids;
    }

    /**
     * Generated from protobuf field <code>repeated string member_ids = 1;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setMemberIds($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->member_ids = $arr;

        return $this;
    }

}

