<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: room_invitation.proto

namespace Wechaty\Puppet;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>wechaty.puppet.RoomInvitationPayloadRequest</code>
 */
class RoomInvitationPayloadRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string id = 1;</code>
     */
    protected $id = '';
    /**
     * Generated from protobuf field <code>.google.protobuf.StringValue payload = 2;</code>
     */
    protected $payload = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $id
     *     @type \Google\Protobuf\StringValue $payload
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\RoomInvitation::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, True);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.StringValue payload = 2;</code>
     * @return \Google\Protobuf\StringValue
     */
    public function getPayload()
    {
        return $this->payload;
    }

    /**
     * Returns the unboxed value from <code>getPayload()</code>

     * Generated from protobuf field <code>.google.protobuf.StringValue payload = 2;</code>
     * @return string|null
     */
    public function getPayloadUnwrapped()
    {
        return $this->readWrapperValue("payload");
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.StringValue payload = 2;</code>
     * @param \Google\Protobuf\StringValue $var
     * @return $this
     */
    public function setPayload($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\StringValue::class);
        $this->payload = $var;

        return $this;
    }

    /**
     * Sets the field by wrapping a primitive type in a Google\Protobuf\StringValue object.

     * Generated from protobuf field <code>.google.protobuf.StringValue payload = 2;</code>
     * @param string|null $var
     * @return $this
     */
    public function setPayloadUnwrapped($var)
    {
        $this->writeWrapperValue("payload", $var);
        return $this;}

}

