<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: room_invitation.proto

namespace Wechaty\Puppet;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>wechaty.puppet.RoomInvitationPayloadResponse</code>
 */
class RoomInvitationPayloadResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string id = 1;</code>
     */
    protected $id = '';
    /**
     * Generated from protobuf field <code>string inviter_id = 2;</code>
     */
    protected $inviter_id = '';
    /**
     * Generated from protobuf field <code>string topic = 3;</code>
     */
    protected $topic = '';
    /**
     * Generated from protobuf field <code>uint32 member_count = 4;</code>
     */
    protected $member_count = 0;
    /**
     * Generated from protobuf field <code>repeated string member_ids = 5;</code>
     */
    private $member_ids;
    /**
     * Generated from protobuf field <code>uint64 timestamp = 6;</code>
     */
    protected $timestamp = 0;
    /**
     * Generated from protobuf field <code>string avatar = 7;</code>
     */
    protected $avatar = '';
    /**
     * Generated from protobuf field <code>string invitation = 8;</code>
     */
    protected $invitation = '';
    /**
     * Generated from protobuf field <code>string receiver_id = 9;</code>
     */
    protected $receiver_id = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $id
     *     @type string $inviter_id
     *     @type string $topic
     *     @type int $member_count
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $member_ids
     *     @type int|string $timestamp
     *     @type string $avatar
     *     @type string $invitation
     *     @type string $receiver_id
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\RoomInvitation::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>
     * @return string
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>string id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkString($var, True);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string inviter_id = 2;</code>
     * @return string
     */
    public function getInviterId()
    {
        return $this->inviter_id;
    }

    /**
     * Generated from protobuf field <code>string inviter_id = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setInviterId($var)
    {
        GPBUtil::checkString($var, True);
        $this->inviter_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string topic = 3;</code>
     * @return string
     */
    public function getTopic()
    {
        return $this->topic;
    }

    /**
     * Generated from protobuf field <code>string topic = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setTopic($var)
    {
        GPBUtil::checkString($var, True);
        $this->topic = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 member_count = 4;</code>
     * @return int
     */
    public function getMemberCount()
    {
        return $this->member_count;
    }

    /**
     * Generated from protobuf field <code>uint32 member_count = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setMemberCount($var)
    {
        GPBUtil::checkUint32($var);
        $this->member_count = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string member_ids = 5;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getMemberIds()
    {
        return $this->member_ids;
    }

    /**
     * Generated from protobuf field <code>repeated string member_ids = 5;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setMemberIds($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->member_ids = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 timestamp = 6;</code>
     * @return int|string
     */
    public function getTimestamp()
    {
        return $this->timestamp;
    }

    /**
     * Generated from protobuf field <code>uint64 timestamp = 6;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTimestamp($var)
    {
        GPBUtil::checkUint64($var);
        $this->timestamp = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string avatar = 7;</code>
     * @return string
     */
    public function getAvatar()
    {
        return $this->avatar;
    }

    /**
     * Generated from protobuf field <code>string avatar = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setAvatar($var)
    {
        GPBUtil::checkString($var, True);
        $this->avatar = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string invitation = 8;</code>
     * @return string
     */
    public function getInvitation()
    {
        return $this->invitation;
    }

    /**
     * Generated from protobuf field <code>string invitation = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setInvitation($var)
    {
        GPBUtil::checkString($var, True);
        $this->invitation = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string receiver_id = 9;</code>
     * @return string
     */
    public function getReceiverId()
    {
        return $this->receiver_id;
    }

    /**
     * Generated from protobuf field <code>string receiver_id = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setReceiverId($var)
    {
        GPBUtil::checkString($var, True);
        $this->receiver_id = $var;

        return $this;
    }

}

