<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: helloworld.proto

namespace GPBMetadata;

class Helloworld
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
            return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0af8010a1068656c6c6f776f726c642e70726f746f1212776563686174792e68656c6c6f776f726c64221c0a0c48656c6c6f52657175657374120c0a046e616d65180120012809221d0a0a48656c6c6f5265706c79120f0a076d65737361676518012001280932590a0747726565746572124e0a0853617948656c6c6f12202e776563686174792e68656c6c6f776f726c642e48656c6c6f526571756573741a1e2e776563686174792e68656c6c6f776f726c642e48656c6c6f5265706c79220042300a1b696f2e677270632e6578616d706c65732e68656c6c6f776f726c64420f48656c6c6f576f726c6450726f746f5001620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

